"""initial

Revision ID: ecdbe7162ce3
Revises: 
Create Date: 2026-06-24 22:13:48.798950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdbe7162ce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_observability_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_name', sa.String(length=128), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('requested_at_utc', sa.DateTime(), nullable=True),
    sa.Column('responded_at_utc', sa.DateTime(), nullable=True),
    sa.Column('llm_session_id', sa.String(length=128), nullable=True),
    sa.Column('llm_audit_entry_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_observability_log_correlation_id'), 'ai_observability_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_observability_log_feature_name'), 'ai_observability_log', ['feature_name'], unique=False)
    op.create_table('request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('protocol', sa.String(length=8), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('requested_at_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_log_correlation_id'), 'request_log', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_log_correlation_id'), table_name='request_log')
    op.drop_table('request_log')
    op.drop_index(op.f('ix_ai_observability_log_feature_name'), table_name='ai_observability_log')
    op.drop_index(op.f('ix_ai_observability_log_correlation_id'), table_name='ai_observability_log')
    op.drop_table('ai_observability_log')
    # ### end Alembic commands ###
